### ISSUE TITLE
デプロイ後、1日程経つとmilkcocoaのコネクションが切れる

### ISSUE THREAD

**Issue by kiyopikko** [joeartsea/node-red-contrib-milkcocoa#5]
環境は、herokuのHobby($7)プランです。
問題が特定でき次第、報告します。

**Comment by syuhei176** [comment]
storageはファイルですか？mongodbですか？

**Comment by kiyopikko** [comment]
mongodbですね。
後からです。

**Comment by syuhei176** [comment]
てことはrestart時に消えるんじゃないですか？

**Comment by kiyopikko** [comment]
そうなんですか。。どうすればいいでしょうか。

**Comment by syuhei176** [comment]
Herokuに入れる時点でmilkcocoaノードが入っていれば、消えることはないです。具体的なやり方はbuild方法によります。

**Comment by kiyopikko** [comment]
ありがとうございます。確認できたらこのissueは閉じます。

**Comment by kiyopikko** [comment]
確認できました。
